# Site Settings
title: Gregory Albertt CV
url: 'http://suavibe.com/team/gregory'
baseurl: '/gregoryalbertt.github.io' #change it according to your repository name

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
style: styles-6

#Profile information
name: Gregory Albertt
tagline: Full Stack Developer
pic: profile.jpg 
summary: 'Experience in web development (especially with javascript based frameworks), 
Java development and a superficial knowledge in artificial intelligence and data mining. 
Currently, a developer at a VIBE Entertainment and intern at Secretaria de Segurança 
Pública (SSP) do Estado de Alagoas in IT.'

#sidebar links
email: gregory@suavibe.com
phone: +55 82 99925-3626
website:  gregoryalbertt.github.io 
linkedin: gregoryalbertt
github: gregoryalbertt
twitter:
#Update all the sections by editing the files inside _data folder.

# Tracker
analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
